version: "2"

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/acronis/go-appkit/

linters:
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 2
    govet:
      settings:
        printf:
          funcs:
            - (github.com/acronis/go-appkit/log.FieldLogger).Infof
            - (github.com/acronis/go-appkit/log.FieldLogger).Warnf
            - (github.com/acronis/go-appkit/log.FieldLogger).Errorf
            - (github.com/acronis/go-appkit/log.FieldLogger).Debugf
    misspell:
      locale: US
    lll:
      line-length: 140
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
        - experimental
      disabled-checks:
        - paramTypeCombine
        - rangeValCopy
      settings:
        hugeParam:
          sizeThreshold: 256
    funlen:
      lines: 100
      statements: 50

  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - dogsled
          - dupl
          - errcheck
          - funlen
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - govet
          - lll
          - ineffassign
          - noctx
          - unparam
          - unused
